sudo: required
dist: trusty
language: node_js
node_js:
  - '6.10'
branches:
  only:
  - testing
before_install:
  - 'npm install -g npm@latest'
services:
  - mongodb
before_script:
  - sleep 15
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
