sudo: required
dist: trusty
language: node_js
node_js:
  - '6.10'
branches:
  only:
  - testing
notifications:
  email:
    - cjjordan234@gmail.com
    - ewrenn@wisc.edu
    - ivanpereda95@gmail.com
    - kgao9@wisc.edu
    - lstefanski@wisc.edu
    - oscarjuarez66@gmail.com
before_install:
  - 'npm install -g npm@latest'
services:
  - mongodb
before_script:
  - sleep 15
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
